version: '3'

services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:user@localhost:5432/quiz_questions
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: quiz_questions
    ports:
      - "5432:5432"
